include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude: [lib/**.freezed.dart, lib/**.g.dart, lib/**.gen.dart, lib/**.gr.dart]

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-parameters: 10
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - double-literal-format
    - no-boolean-literal-compare
    - no-equal-then-else
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    - prefer-correct-identifier-length:
        max-identifier-length: 50
        min-identifier-length: 2
    - prefer-correct-type-name
    - prefer-first
    - prefer-last
    - prefer-match-file-name:
        exclude:
          - lib/main.dart
          - lib/core/errors/exceptions.dart
    - prefer-trailing-comma:
        break-on: 6
        severity: style
    - avoid-returning-widgets
    - avoid-wrapping-in-padding
  rules-exclude:
    - test/**
    - lib/common/models/exceptions.dart
    - lib/generated_plugin_registrant.dart

linter:
  rules:
