name: m_sport
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  glass_kit: ^2.0.1
  styled_widget: ^0.4.0+3

dev_dependencies:
  build_runner: ^2.1.10
  dart_code_metrics: ^4.15.0
  flutter_gen_runner: ^4.1.6
  flutter_svg: ^1.0.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: RubikGlitch
      fonts:
        - asset: assets/fonts/RubikGlitch-Regular.ttf