name: insight
description: Future learning platform

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_bounce_widget: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.0+1
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  glass: ^1.0.1+1
  insight_player:
    path: packages/insight_player
  provider: ^6.0.3
  shimmer: ^2.0.0
  video_player: ^2.4.2
  cached_network_image: ^3.2.3
  rest_client:
    path: packages/rest_client
  auth_client:
    path: packages/auth_client
  database:
    path: packages/database
  dio: ^5.1.1
  

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.0
  flutter_gen_runner: ^5.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mocktail_image_network: ^0.3.1
  bloc_test: ^9.1.3
  mockito: ^5.4.1

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: RubikGlitch
      fonts:
        - asset: assets/fonts/Rubik_Glitch/RubikGlitch-Regular.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/fitness_splash.png

  android_12:
    icon_background_color: "#ffffff"
    image: assets/images/fitness_splash.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/insight_logo.png"
