name: insight
description: Future learning platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  insight_player:
    path: packages/insight_player
  dartz: ^0.10.1
  get_it: ^7.2.0
  glass_kit: ^2.0.1
  styled_widget: ^0.4.0+3
  internet_connection_checker: ^1.0.0+1
  flutter_native_splash: ^2.2.0+1
  retrofit: '>=3.0.0 <4.0.0'
  video_player: ^2.4.2
  shimmer: ^2.0.0
  firebase_core: ^2.4.0
  freezed_annotation: ^2.2.0
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.3
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.11.0
  dio: ^4.0.6
  flutter_screenutil: ^5.7.0
  glass: ^1.0.1+1
  flutter_svg: ^2.0.3

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.2.0
  mobx_codegen: ^2.0.7
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: RubikGlitch
      fonts:
        - asset: assets/fonts/Rubik_Glitch/RubikGlitch-Regular.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/fitness_splash.png
  
  android_12:
    icon_background_color: "#ffffff"
    image: assets/images/fitness_splash.png
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/insight_logo.png"