name: m_sport
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  cupertino_icons: ^1.0.2
  app_links: ^3.2.0
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  get_it: ^7.2.0
  glass_kit: ^2.0.1
  styled_widget: ^0.4.0+3
  internet_connection_checker: ^0.0.1+3
  flutter_native_splash: ^2.2.0+1
  responsive_sizer: ^3.0.8
  retrofit: '>=3.0.0 <4.0.0'
  video_player: ^2.4.2
  shimmer: ^2.0.0
  firebase_core: ^1.17.1
  freezed_annotation: ^2.0.3
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.3
  equatable: ^2.0.3

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.10
  dart_code_metrics: ^4.15.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  flutter_gen_runner: ^4.1.6
  flutter_svg: ^1.0.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  mobx_codegen: ^2.0.7
  mocktail: ^0.3.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: RubikGlitch
      fonts:
        - asset: assets/fonts/Rubik_Glitch/RubikGlitch-Regular.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/fitness_splash.png
  
  android_12:
    icon_background_color: "#ffffff"
    image: assets/images/fitness_splash.png