name: insight
description: Future learning platform

publish_to: "none"

version: 2.3.2-beta

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # Network
  dio: ^5.1.1

  # Navigation
  go_router: ^13.2.0

  # BLoC
  bloc: ^8.1.4
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.2

  # firebase
  firebase_core: ^2.27.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_auth: ^4.7.2
  firebase_core_platform_interface: ^5.0.0

  # DB
  shared_preferences: ^2.2.3

  # Utils
  equatable: ^2.0.3
  provider: ^6.0.3
  meta: ^1.9.1
  stack_trace: ^1.11.0
  image_picker: ^1.0.7
  permission_handler: ^11.1.0
  flutter_image_compress: ^2.3.0

  # UI
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.5
  flutter_bounce_widget: ^1.0.2
  flutter_native_splash: ^2.2.0+1
  insight_player:
    path: packages/insight_player
  insight_snackbar: ^2.0.1
  video_player: ^2.8.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mocktail_image_network: ^1.1.0
  bloc_test: ^9.1.3
  mockito: ^5.4.2
  pubspec_generator: ^4.0.0

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  shaders:
    - assets/shaders/shimmer.frag

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: RubikGlitch
      fonts:
        - asset: assets/fonts/Rubik_Glitch/RubikGlitch-Regular.ttf

flutter_native_splash:
  color: "#1C1C1E"
  image: assets/images/insight_logo.png

  android_12:
    icon_background_color: "#1C1C1E"
    image: assets/images/insight_logo.png
