name: insight_player
description: Beautiful player. Made for the Insight app
version: 0.0.1
homepage: lib/insight_player.dart

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: 2.8.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
