// Mocks generated by Mockito 5.4.1 from annotations
// in insight/test/unit/categories/bloc/categories_bloc_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:insight/features/categories/data/datasources/categories_remote_datasource.dart'
    as _i2;
import 'package:insight/features/categories/data/repositories/categories_repository.dart'
    as _i3;
import 'package:insight/features/categories/domain/entities/category_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoriesRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.CategoriesRemoteDataSource {
  _FakeCategoriesRemoteDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoriesRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesRepositoryImpl extends _i1.Mock
    implements _i3.CategoriesRepositoryImpl {
  MockCategoriesRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoriesRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeCategoriesRemoteDataSource_0(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i2.CategoriesRemoteDataSource);
  @override
  _i4.Future<List<_i5.CategoryEntity>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.CategoryEntity>>.value(<_i5.CategoryEntity>[]),
      ) as _i4.Future<List<_i5.CategoryEntity>>);
}
