on: 
  pull_request:
    branches:
      - main
  
name: CI
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Get dependencies
      run: flutter pub get

    - name: Generating
      run: flutter packages pub run build_runner build --delete-conflicting-outputs

    - name: Analyze
      run: flutter analyze

    - name: Testing
      run: flutter test

  test-unit:
    name: Unit tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter test
