on: pull_request
name: Build and Release apk
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"

    - name: Get dependencies
      run: flutter pub get

    - run: flutter packages pub run build_runner build

    - run: flutter analyze

    - name: Build APK
      run: flutter build apk
    - uses: actions/upload-artifact@v3
      with:
        name: app
        path: /home/runner/work/m_sport/m_sport/build/app/outputs/apk/release/app-release.apk

  distribution:
    name: Upload to Firebase App Distribution
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download
      uses: actions/download-artifact@v3
      with:
        name: app
    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.3
      with:
        appId: ${{secrets.FIREBASE_ANDROID_PROD_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: app-release.apk